name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download npm package artifact
        uses: actions/download-artifact@v4
        with:
          name: npm-package
          path: ./npm-package

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd npm-package
          PACKAGE_NAME=$(ls *.tgz)
          echo "Publishing $PACKAGE_NAME to npm..."
          npm publish "$PACKAGE_NAME"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: npm-package/*.tgz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}